In [40]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [41]:
df = pd.read_csv("houseprice.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  680000
4  4000       5.0    8  725000

In [42]:
# data pre processing ->handle missing values (NaN)

In [43]:
# math.floor to get integer value and not float for mdian bedroom
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [44]:
# fill NaN with median_bedroom value
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  680000
4  4000       5.0    8  725000

In [45]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [46]:
# m->sope or coefficient

reg.coef_

array([  143.625, -6762.5  ,   337.5  ])

In [47]:
# b ->intercept

reg.intercept_

173112.50000000006

In [48]:
reg.predict([[3000, 4, 15]])

array([582000.])

In [49]:
# price= m1 * area + m2 * bedroom + m3 * age + b

143.625*3000 + -6762.5*4 + 337.5*15 + 173112.50000000006

582000.0

In [50]:
reg.predict([[2600, 3, 5]])

array([527937.5])

In [51]:
reg.predict([[7000, 2, 20]])

array([1171712.5])

In [52]:
def house_price(area, bedrooms, age):
    price=reg.predict([[area, bedrooms, age]])
    val= price[0].round(2)
    return (" Rs.{}".format(val))


In [53]:
house_price(3000, 2, 10)

' Rs.593837.5'