In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("houseprice.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  680000
4  4000       5.0    8  725000

In [3]:
# data pre processing ->handle missing values (NaN)

In [4]:
# math.floor to get integer value and not float for mdian bedroom
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [5]:
# fill NaN with median_bedroom value
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  680000
4  4000       5.0    8  725000

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [7]:
# m->sope or coefficient

reg.coef_

array([  143.625, -6762.5  ,   337.5  ])

In [8]:
# b ->intercept

reg.intercept_

173112.50000000006

In [9]:
reg.predict([[3000, 4, 15]])

C:\Users\shruti.randive\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\base.py:446: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([582000.])

In [10]:
# price= m1 * area + m2 * bedroom + m3 * age + b

143.625*3000 + -6762.5*4 + 337.5*15 + 173112.50000000006

582000.0

In [11]:
reg.predict([[2600, 3, 5]])

C:\Users\shruti.randive\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\base.py:446: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([527937.5])